### PR TITLE
add cargo lock and specify old version of clap

### PR DESCRIPTION
**Pull request by kiliankoe**
unfortunately this won't compile with newer versions of clap 😞

### CODE REVIEW

**Comment by hoodie** [comment]
it doesn't? mine does? what's the error?

**Comment by kiliankoe** [comment]
You probably have an old cargo.lock specifying which version of clap to use? Just a guess. But since you intentionally left it out of the repo I don't know. Try deleting it and rebuilding with your very generous clap version requirement of `*`.

**Comment by hoodie** [comment]
I did that with `cargo update`, and then built with `cargo build --example random_player` and it builds with clap `2.1.2`.
This was initially a bin crate, so the `Cargo.lock` automatically in the `.gitignore`.
As I said, on my end it builds with the latest clap, what is the error on your site when you try to build with clap `2.x` ?

**Comment by kiliankoe** [comment]
As you know seeing how you were sitting right next to me only moments ago, this no longer applies 😄

**Pull request closed without merging**
